# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 819d8b03bac7ee8d93a6d1a9cc0dcb822259fccc4d9566ab7edf59791110537cccec5879fa55b9b69da0c384b445ba6d8ce8c2a31d66f45f03c24d9e5ce09efc

test:
  secret_key_base: f63e4142a3034111c80054d3257d1e2de454880e594dc126953a41c9fbd996578b15a543ad5950f91a8aacb8802451cbb5ec9a89c37344e515dcdc47e836d399

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
